services:
  frontend:
    build: "C:/School/Semester 4/Opdrachten/Persoonlijke opdracht/BuffelSimulatorFrontend"
    container_name: buffelfrontend
    ports:
      - "4200:4200"
    command: npm start
    depends_on:
      - backend

  backend:
    build: "C:/School/Semester 4/Opdrachten/Persoonlijke opdracht/BuffelSimulatorBackend"
    container_name: buffelbackend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/buffel
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: buffel-db
    environment:
      POSTGRES_DB: buffel
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
